name: Add Artifact to Repo

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: your-artifact-name  # replace with your actual artifact name
        path: .
        tag: ${{ github.event.inputs.tag }}

    - name: Add Artifact to Repository
      run: |
        git add .
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git commit -m "Add artifact to repository"
        git push
