name: Add Artifact to Repo

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: CushItRealGood/ghpages-test
        ref: ${{ github.event.inputs.tag }}
        token: ${{ secrets.GHCR_TOKEN }}

    - name: Create Branch
      run: |
        git branch new-branch
        git checkout new-branch
        
    - name: Download Artifact
      run: |
        tag=${{ github.event.inputs.tag }}
        response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/$tag")
        echo "GitHub API response: $response"
        asset_url=$(echo "$response" | jq -r '.assets[] | select(.name == "app-artifact.zip").browser_download_url')
        echo "Downloading artifact from URL: $asset_url"
        curl -sLJO -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$asset_url"

    - name: Move Artifact to gh-pages Directory
      run: |
        mkdir gh-pages
        mv app-artifact.zip gh-pages/
        
    - name: Add Artifact to Repository
      run: |
        git add gh-pages/
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git commit -m "Add artifact to repository"
        git fetch origin new-branch
        git merge --no-ff origin/new-branch
        git push origin new-branch
