name: Add Artifact to Repo

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: CushItRealGood/ghpages-test
        ref: ${{ github.event.inputs.tag }}
        token: ${{ secrets.GHCR_TOKEN }}

   # - name: Download Artifact
   #   uses: actions/download-artifact@v2
   #   with:
   #     name: app-artifact.zip  # replace with your actual artifact name
   #     path: .
   #     tag: ${{ github.event.inputs.tag }}
    - name: Download Artifact
      run: |
        tag=${{ github.event.inputs.tag }}
        response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/$tag")
        echo "GitHub API response: $response"
        asset_id=$(echo "$response" | jq -r '.assets[] | select(.name == "app-artifact.zip").id')
        echo "Downloading artifact with ID: $asset_id"
        curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -LJO "https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id"
          
    - name: Add Artifact to Repository
      run: |
        git add .
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git commit -m "Add artifact to repository"
        git push
